[project]
name = "roi-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.138.0",
    "fastmcp>=3.4.2",
    "langchain-mcp-adapters>=0.3.0",
    "langgraph>=0.4.0",
    "langchain-openai>=0.3.0",
    "langchain-community>=0.3.0",
]
